import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const monument = localFont({
  src: [
    {
      path: "./fonts/MonumentExtended-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/MonumentExtended-Ultrabold.otf",
      weight: "800",
      style: "extrabold",
    },
  ],
  variable: "--font-monument",
  display: "swap",
});

const gotham = localFont({
  src: [
    { path: "./fonts/Gotham-XLight.otf", weight: "200", style: "normal" },
    { path: "./fonts/Gotham-Light.otf", weight: "300", style: "normal" },
    { path: "./fonts/GothamBook.ttf", weight: "400", style: "normal" },
    { path: "./fonts/GothamMedium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/Gotham-Bold.otf", weight: "700", style: "normal" },
    { path: "./fonts/Gotham-Black.otf", weight: "900", style: "normal" },
    { path: "./fonts/GothamBookItalic.ttf", weight: "400", style: "italic" },
    { path: "./fonts/GothamMediumItalic.ttf", weight: "500", style: "italic" },
    { path: "./fonts/GothamBoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-gotham",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${monument.variable} ${gotham.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
